server:
  port: 8089

logging:
  level:
    ROOT: DEBUG
  file:
    path: ./log

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: localhost:29200
easy-es:
  enable: true # 是否开启EE自动配置
  address : 127.0.0.1:9200 # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
  schema: http # 默认为http
