server:
  port: 8086

spring:
  application:
    name: citel11
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      primary: master
      datasource:
        master:
          jdbc-url: jdbc:mysql://47.94.133.217:3306/vocational_education_biz_jq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          url: jdbc:mysql://47.94.133.217:3306/vocational_education_biz_jq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: Dms#2023
          driver-class-name: com.mysql.cj.jdbc.Driver



#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 25
      max-wait: 60000
      use-unfair-lock: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型
      id-type: auto

